# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-bDYnrD6iDH5hGs2l_iIRpCZAbj6TmlT
"""

x = 5
print(f"變數x的值是:{x}")

print(f"變數x的記憶體地址是:{id(x)}")